def getBuildConfig() {
	if(env.BRANCH_NAME == "master") {
		return "Release"
	}
	return "Debug"
}

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5'))
    }
    agent {
	    node {
            label 'nuget&&msbuild&&windows'
		}
    }
	environment {
		BUILD_CONFIG = getBuildConfig()
	}
    stages {
        stage('Clean') {
            steps {
                 bat "nuget restore"
                 bat "msbuild TusClient.proj /p:Config=${env.BUILD_CONFIG} /t:Clean"
            }
        }
        stage('compile & build locally') {
            steps {
                 bat "msbuild TusClient.proj /p:Config=${env.BUILD_CONFIG} /t:Build"
            }
        }
        stage('Publish') {
            steps {
                 bat "msbuild TusClient.proj /p:Config=${env.BUILD_CONFIG} /t:Publish"
            }
        }
    }
}
